// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: pathfinder_service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PathFinder_CalculateTrajectory_FullMethodName   = "/PathFinder/CalculateTrajectory"
	PathFinder_CalculateSplinePoints_FullMethodName = "/PathFinder/CalculateSplinePoints"
)

// PathFinderClient is the client API for PathFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PathFinderClient interface {
	CalculateTrajectory(ctx context.Context, in *TrajectoryRequest, opts ...grpc.CallOption) (*TrajectoryResponse, error)
	CalculateSplinePoints(ctx context.Context, in *SplineRequest, opts ...grpc.CallOption) (*SplineResponse, error)
}

type pathFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewPathFinderClient(cc grpc.ClientConnInterface) PathFinderClient {
	return &pathFinderClient{cc}
}

func (c *pathFinderClient) CalculateTrajectory(ctx context.Context, in *TrajectoryRequest, opts ...grpc.CallOption) (*TrajectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrajectoryResponse)
	err := c.cc.Invoke(ctx, PathFinder_CalculateTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pathFinderClient) CalculateSplinePoints(ctx context.Context, in *SplineRequest, opts ...grpc.CallOption) (*SplineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplineResponse)
	err := c.cc.Invoke(ctx, PathFinder_CalculateSplinePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathFinderServer is the server API for PathFinder service.
// All implementations must embed UnimplementedPathFinderServer
// for forward compatibility.
type PathFinderServer interface {
	CalculateTrajectory(context.Context, *TrajectoryRequest) (*TrajectoryResponse, error)
	CalculateSplinePoints(context.Context, *SplineRequest) (*SplineResponse, error)
	mustEmbedUnimplementedPathFinderServer()
}

// UnimplementedPathFinderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPathFinderServer struct{}

func (UnimplementedPathFinderServer) CalculateTrajectory(context.Context, *TrajectoryRequest) (*TrajectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateTrajectory not implemented")
}
func (UnimplementedPathFinderServer) CalculateSplinePoints(context.Context, *SplineRequest) (*SplineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSplinePoints not implemented")
}
func (UnimplementedPathFinderServer) mustEmbedUnimplementedPathFinderServer() {}
func (UnimplementedPathFinderServer) testEmbeddedByValue()                    {}

// UnsafePathFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathFinderServer will
// result in compilation errors.
type UnsafePathFinderServer interface {
	mustEmbedUnimplementedPathFinderServer()
}

func RegisterPathFinderServer(s grpc.ServiceRegistrar, srv PathFinderServer) {
	// If the following call pancis, it indicates UnimplementedPathFinderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PathFinder_ServiceDesc, srv)
}

func _PathFinder_CalculateTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathFinderServer).CalculateTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathFinder_CalculateTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathFinderServer).CalculateTrajectory(ctx, req.(*TrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PathFinder_CalculateSplinePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathFinderServer).CalculateSplinePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathFinder_CalculateSplinePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathFinderServer).CalculateSplinePoints(ctx, req.(*SplineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PathFinder_ServiceDesc is the grpc.ServiceDesc for PathFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PathFinder",
	HandlerType: (*PathFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateTrajectory",
			Handler:    _PathFinder_CalculateTrajectory_Handler,
		},
		{
			MethodName: "CalculateSplinePoints",
			Handler:    _PathFinder_CalculateSplinePoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pathfinder_service.proto",
}
