// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: PathFinder.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PathFinder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_PathFinder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_PathFinder_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TrajectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segments []*TrajectoryRequest_Segment `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
}

func (x *TrajectoryRequest) Reset() {
	*x = TrajectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PathFinder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryRequest) ProtoMessage() {}

func (x *TrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PathFinder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryRequest.ProtoReflect.Descriptor instead.
func (*TrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_PathFinder_proto_rawDescGZIP(), []int{1}
}

func (x *TrajectoryRequest) GetSegments() []*TrajectoryRequest_Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type TrajectoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrajectoryResponse) Reset() {
	*x = TrajectoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PathFinder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrajectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryResponse) ProtoMessage() {}

func (x *TrajectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PathFinder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryResponse.ProtoReflect.Descriptor instead.
func (*TrajectoryResponse) Descriptor() ([]byte, []int) {
	return file_PathFinder_proto_rawDescGZIP(), []int{2}
}

type TrajectoryRequest_Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position   *Vector `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	ControlIn  *Vector `protobuf:"bytes,2,opt,name=controlIn,proto3" json:"controlIn,omitempty"`
	ControlOut *Vector `protobuf:"bytes,3,opt,name=controlOut,proto3" json:"controlOut,omitempty"`
	UseHeading bool    `protobuf:"varint,4,opt,name=useHeading,proto3" json:"useHeading,omitempty"`
	Heading    float32 `protobuf:"fixed32,5,opt,name=heading,proto3" json:"heading,omitempty"`
}

func (x *TrajectoryRequest_Point) Reset() {
	*x = TrajectoryRequest_Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PathFinder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrajectoryRequest_Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryRequest_Point) ProtoMessage() {}

func (x *TrajectoryRequest_Point) ProtoReflect() protoreflect.Message {
	mi := &file_PathFinder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryRequest_Point.ProtoReflect.Descriptor instead.
func (*TrajectoryRequest_Point) Descriptor() ([]byte, []int) {
	return file_PathFinder_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TrajectoryRequest_Point) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *TrajectoryRequest_Point) GetControlIn() *Vector {
	if x != nil {
		return x.ControlIn
	}
	return nil
}

func (x *TrajectoryRequest_Point) GetControlOut() *Vector {
	if x != nil {
		return x.ControlOut
	}
	return nil
}

func (x *TrajectoryRequest_Point) GetUseHeading() bool {
	if x != nil {
		return x.UseHeading
	}
	return false
}

func (x *TrajectoryRequest_Point) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type TrajectoryRequest_Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*TrajectoryRequest_Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *TrajectoryRequest_Segment) Reset() {
	*x = TrajectoryRequest_Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PathFinder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrajectoryRequest_Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrajectoryRequest_Segment) ProtoMessage() {}

func (x *TrajectoryRequest_Segment) ProtoReflect() protoreflect.Message {
	mi := &file_PathFinder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrajectoryRequest_Segment.ProtoReflect.Descriptor instead.
func (*TrajectoryRequest_Segment) Descriptor() ([]byte, []int) {
	return file_PathFinder_proto_rawDescGZIP(), []int{1, 1}
}

func (x *TrajectoryRequest_Segment) GetPoints() []*TrajectoryRequest_Point {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_PathFinder_proto protoreflect.FileDescriptor

var file_PathFinder_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x61, 0x74, 0x68, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x24, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0xc1, 0x02, 0x0a, 0x11, 0x54, 0x72, 0x61,
	0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36,
	0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x54, 0x72, 0x61, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xb6, 0x01, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x49, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x49, 0x6e, 0x12, 0x27, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x4f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x1a,
	0x3b, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x54, 0x72, 0x61,
	0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x54, 0x72, 0x61, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x4e, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x68, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x40, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x2e, 0x54, 0x72, 0x61, 0x6a, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x54, 0x72,
	0x61, 0x6a, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PathFinder_proto_rawDescOnce sync.Once
	file_PathFinder_proto_rawDescData = file_PathFinder_proto_rawDesc
)

func file_PathFinder_proto_rawDescGZIP() []byte {
	file_PathFinder_proto_rawDescOnce.Do(func() {
		file_PathFinder_proto_rawDescData = protoimpl.X.CompressGZIP(file_PathFinder_proto_rawDescData)
	})
	return file_PathFinder_proto_rawDescData
}

var file_PathFinder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_PathFinder_proto_goTypes = []interface{}{
	(*Vector)(nil),                    // 0: Vector
	(*TrajectoryRequest)(nil),         // 1: TrajectoryRequest
	(*TrajectoryResponse)(nil),        // 2: TrajectoryResponse
	(*TrajectoryRequest_Point)(nil),   // 3: TrajectoryRequest.Point
	(*TrajectoryRequest_Segment)(nil), // 4: TrajectoryRequest.Segment
}
var file_PathFinder_proto_depIdxs = []int32{
	4, // 0: TrajectoryRequest.segments:type_name -> TrajectoryRequest.Segment
	0, // 1: TrajectoryRequest.Point.position:type_name -> Vector
	0, // 2: TrajectoryRequest.Point.controlIn:type_name -> Vector
	0, // 3: TrajectoryRequest.Point.controlOut:type_name -> Vector
	3, // 4: TrajectoryRequest.Segment.points:type_name -> TrajectoryRequest.Point
	1, // 5: PathFinder.CalculateTrajectory:input_type -> TrajectoryRequest
	2, // 6: PathFinder.CalculateTrajectory:output_type -> TrajectoryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_PathFinder_proto_init() }
func file_PathFinder_proto_init() {
	if File_PathFinder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PathFinder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PathFinder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrajectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PathFinder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrajectoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PathFinder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrajectoryRequest_Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PathFinder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrajectoryRequest_Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PathFinder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PathFinder_proto_goTypes,
		DependencyIndexes: file_PathFinder_proto_depIdxs,
		MessageInfos:      file_PathFinder_proto_msgTypes,
	}.Build()
	File_PathFinder_proto = out.File
	file_PathFinder_proto_rawDesc = nil
	file_PathFinder_proto_goTypes = nil
	file_PathFinder_proto_depIdxs = nil
}
