name: "Build & Release"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - uses: subosito/flutter-action@v2
              with:
                flutter-version: "3.16.0"
                channel: 'stable'
                cache: true

            - name: Build
              run: sh ./scripts/auto.sh
              shell: bash
            
            - name: Compress
              uses: vimtor/action-zip@v1.1
              with:
                files: dist-Release/
                dest: release.zip
    
            - name: Release
              uses: ncipollo/release-action@v1
              with: 
                artifacts: "release.zip"
                tag: v1.0.${{ github.run_number }}
                token: ${{ secrets.GITHUB_TOKEN }}