name: "Build & Release"

on:
    push:
        branches:
            - main
        paths:
            - '**.dart'
            - '**.yml'
            - '**.go'
            - '**.mod'
            - '**.sh'
    pull_request:
        types: 
            - closed
        branches:
            - main
        paths: 
           - '**.dart'
           - '**.yml'
           - '**.go'
           - '**.mod'
           - '**.sh'
        

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                flutter-version: "3.16.0"
                channel: 'stable'
                cache: true

            - name: Build
              run: sh ./scripts/auto.sh
              shell: bash
            
            - name: Compress
              uses: vimtor/action-zip@v1.1
              with:
                files: dist-Release
                dest: release.zip
    
            - name: Release
              uses: ncipollo/release-action@v1
              with: 
                artifacts: "release.zip"
                tag: v1.${{ vars.VERSION }}.${{ github.run_number }}
                token: ${{ secrets.GITHUB_TOKEN }}